onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /cmd_tb/clk
add wave -noupdate /cmd_tb/rst
add wave -noupdate /cmd_tb/rstn
add wave -noupdate /cmd_tb/tx_busy
add wave -noupdate /cmd_tb/s_tdata
add wave -noupdate /cmd_tb/s_tvalid
add wave -noupdate /cmd_tb/s_tready
add wave -noupdate /cmd_tb/m_tdata
add wave -noupdate /cmd_tb/m_tvalid
add wave -noupdate /cmd_tb/m_tready
add wave -noupdate /cmd_tb/rx_busy
add wave -noupdate /cmd_tb/rx_overrun_error
add wave -noupdate /cmd_tb/rx_frame_error
add wave -noupdate /cmd_tb/s_cmd_Addr
add wave -noupdate /cmd_tb/s_cmd_start
add wave -noupdate /cmd_tb/s_cmd_read
add wave -noupdate /cmd_tb/s_cmd_write
add wave -noupdate /cmd_tb/s_cmd_write_multiple
add wave -noupdate /cmd_tb/s_cmd_stop
add wave -noupdate /cmd_tb/s_cmd_valid
add wave -noupdate /cmd_tb/s_cmd_ready
add wave -noupdate /cmd_tb/s_cmd_tdata
add wave -noupdate /cmd_tb/s_cmd_tvalid
add wave -noupdate /cmd_tb/s_cmd_tready
add wave -noupdate /cmd_tb/s_cmd_tlast
add wave -noupdate /cmd_tb/m_cmd_tdata
add wave -noupdate /cmd_tb/m_cmd_tvalid
add wave -noupdate /cmd_tb/m_cmd_tready
add wave -noupdate /cmd_tb/m_cmd_tlast
add wave -noupdate /cmd_tb/s_axis_tdata
add wave -noupdate /cmd_tb/s_axis_tvalid
add wave -noupdate /cmd_tb/s_axis_tready
add wave -noupdate /cmd_tb/m_axis_tdata
add wave -noupdate /cmd_tb/m_axis_tvalid
add wave -noupdate /cmd_tb/m_axis_tready
add wave -noupdate /cmd_tb/rxd
add wave -noupdate /cmd_tb/txd
add wave -noupdate /cmd_tb/rs_axis_tdata
add wave -noupdate /cmd_tb/rs_axis_tvalid
add wave -noupdate /cmd_tb/rs_axis_tready
add wave -noupdate /cmd_tb/scl_i
add wave -noupdate /cmd_tb/scl_o
add wave -noupdate /cmd_tb/scl_t
add wave -noupdate /cmd_tb/sda_i
add wave -noupdate /cmd_tb/sda_o
add wave -noupdate /cmd_tb/sda_t
add wave -noupdate /cmd_tb/busy
add wave -noupdate /cmd_tb/bus_control
add wave -noupdate /cmd_tb/bus_active
add wave -noupdate /cmd_tb/missed_ack
add wave -noupdate /cmd_tb/prescale
add wave -noupdate /cmd_tb/stop_on_idle
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {314018630 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {641618227 ps}
